### ISSUE TITLE
Turret Sounds Too Loud

### ISSUE THREAD

**Issue by nathangeranis** [xiaoxiao921/BadAssEngi#1]
The issue I am facing is that the turret sounds do not scale with your in-game SFX sound level, so even if I have the sound level set at 10%, the sound still comes through as if it's 100%. Playing in multiplayer for context. Issue prevalent in single player as well. Happens on the new turret's, but not the default weak boi.

**Comment by xiaoxiao921** [comment]
Hi.
We have a big update coming up and it should be fixed !

**Comment by xiaoxiao921** [comment]
https://thunderstore.io/package/xiaoxiao921/BadAssEngi/
